language: node_js
node_js:
  - "8"
before_script:
  - npm install -g eslint
  #- npm install -g karma
script: true
  #- npm run build
  #- npm run test
  #- npm run lint
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

